name: Suggestion liée au contenu
description: Pour suggérer un ajout de contenu ou une modification de contenu existant.
title: "[Contenu]: "
labels: ["contenu"]
assignees:
  - mihersch
  - redelmann
body:
  - type: markdown
    attributes:
      value: |
        **Remarque**: pour les demandes plus complexes, nous vous invitons à dialoguer avec nous via [Discord](https://discord.gg/b8qu79t6HQ) ou sur [modulo-team@epfl.ch](mailto:contact@modulo-info.ch).
  - type: input
    id: page
    attributes:
      label: Page
      description: Quelle est la page ou la section concernée ?
      placeholder: Nom de la page / URL
    validations:
      required: true
  - type: textarea
    id: probleme
    attributes:
      label: Quel est le problème relevé ?
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Quelle est votre suggestion ?
    validations:
      required: true
